config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    post "users/upload", to: "users/registrations#upload", as: "upload_registration"
    post "users/disconnect" => 'users/registrations#disconnect', as: "disconnect_provider"
  end

  get 'welcome/index'
  root 'welcome#index'

  get 'index' => 'welcome#index'
  get 'sp' => 'sp#index'
  get 'confirm' => 'confirm#show'
  get 'mypage' => 'mypages#show'
  get 'terms' => 'terms#show'
  get 'privacy' => 'privacy#show'

  resources :communities, :only => [:new, :create, :show, :edit, :update, :destroy] do
    resources :boards, :only => [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :t_cards, :only => [:edit, :update]

  post 'communities/:id/tasks/:t_card_id/toggle' => 'communities#toggle'
  get 'communities/:id/refresh_tasks' => 'communities#refresh_tasks'
  get 'communities/:id/invitable_users' => 'communities#invitable_users'
  post 'communities/:id/invite' => 'communities#invite'
  post 'communities/:id/accept' => 'communities#accept'
  post 'communities/:id/decline' => 'communities#decline'
  post 'communities/:id/leave' => 'communities#leave'
  post 'communities/:id/remove' => 'communities#remove'
  get 'communities/:id/members' => 'communities#members'
  
  post 'mypage/tasks/:id/toggle' => 'mypages#toggle'
  get 'mypage/refresh_tasks' => 'mypages#refresh_tasks'

  mount ActionCable.server => '/cable'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/t_card.rb
class TCard < ApplicationRecord
  extend Enumerize
  enumerize :status, in: [:open, :closed], default: :open
  belongs_to :board
  belongs_to :owner, :class_name => 'User'
  has_one :tcard_assignee, dependent: :delete
  has_one :user, :through => :tcard_assignee
  has_many :likes, :as => :likable, dependent: :delete_all

  after_create_commit { CardBroadcastJob.perform_later self }
  after_update_commit { UpdateCardBroadcastJob.perform_later self }

  def assign(user)
    ActiveRecord::Base.transaction do
      # 担当者が割り当てられている場合は、削除してからアサインする
      if self.tcard_assignee
        TcardAssignee.delete(self.tcard_assignee)
      end
      TcardAssignee.create(
        t_card_id: self.id,
        user_id: user.id
      )
    end
  end

  def remove_assign
    ActiveRecord::Base.transaction do
      # 元から担当者が設定されている場合だけ処理する
      unless self.user.blank?
        tcard_assignee = TcardAssignee.find_by(t_card_id: self.id, user_id: self.user.id)
        if tcard_assignee
          TcardAssignee.delete(tcard_assignee)
        end
      end
    end
  end

  class << self
    def update_status(t_card_id)
      @t_card = TCard.find(t_card_id)
      # statusの値をひっくり返す
      @t_card.status = @t_card.status.open? ? TCard.status.closed : TCard.status.open
      @t_card.save
      return @t_card
    end
  end
end

app/controllers/t_cards_controller.rb
class TCardsController < ApplicationController
  before_action :authenticate_user!, :exists_task?, :belongs_to?, :side_column, only: [:edit, :update]

  def edit
    @task = TCard.find(params[:id])
    @community_users = @task.board.community.find_joining_users
    respond_to do |format|
      format.js { render template: "t_cards/_modal_edit", :locals => {:task => @task, :community_users => @community_users, chaindata: params[:chaindata]} }
    end
  end

  def update
    t_card = TCard.find(params[:id])
    # 担当者に変更がある場合だけ
    unless t_card.try(:user).try(:id).to_s == params[:tcard_assignee][:user_id]
      if params[:tcard_assignee][:user_id].blank?
        # 担当者を外す
        t_card.remove_assign
      else
        # 他の人にアサイン
        user = User.find_by(id: params[:tcard_assignee][:user_id])
        t_card.assign(user)
      end
    end

    top_of_assignees = t_card.board.community.find_top_of_assignees
    labels = top_of_assignees[:top_of_assignees].map{|ta| ta[:name]}
    data = top_of_assignees[:top_of_assignees].map{|ta| ta[:count]}

    if t_card.update_attributes(t_card_params) then
      respond_to do |format|
        flash.now[:notice] = t('t_card.update.success')
        format.js { render template: "t_cards/_t_card", :locals => {t_card: TCard.find(params[:id]), title: t('community.well_balanced.title'), labels: labels.to_json.html_safe, data: data, chaindata: params[:chaindata]} }
      end
    else
      flash.now[:notice] = t('t_card.update.failure')
    end

  end

  private
    def t_card_params
      params.require(:t_card).permit(:id, :title, :detail, :deadline, :status)
    end

    def exists_task?
      # if task does not exists, raise RecordNotFound error
      TCard.find(params[:id])
    end

    def belongs_to?
      tcard = TCard.find(params[:id])
      unless current_user.joining?(tcard.board.community)
        raise Forbidden
      end
    end
end

app/views/t_cards/_modal_edit.html.erb
<div class="modal__overlay" tabindex="-1" data-micromodal-close>
  <div class="modal__container mdl-shadow--8dp" role="dialog" aria-modal="true" aria-labelledby="modal-1-title">
    <header class="modal__header">
      <h2 class="modal__title" id="modal-1-title">
        <%= t('t_card.edit.title') %>
      </h2>
      <button class="modal__close" aria-label="Close modal" data-micromodal-close></button>
    </header>
    <main class="modal__content" id="modal-1-content">
      <% if task %>
        <%= form_for(task, html: {id: 'form_edit_task', data: { remote: true }} ) do |f| %>
          <% if !chaindata.nil? %>
            <% chaindata.each do |k, v| %>
              <input type="hidden" name="chaindata[<%= k %>]" value="<%= v %>">
            <% end %>
          <% end %>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <%= f.text_area :title, class: "mdl-textfield__input", rows: 3, maxlength: 255, required: true %>
            <%= f.label :title, class: "mdl-textfield__label" %>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <%= f.text_field :deadline, class: "mdl-textfield__input", id: "datepicker", maxlength: 10, autocomplete: :off %>
            <%= f.label :deadline, class: "mdl-textfield__label" %>
          </div>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label">
            <select class="mdl-selectfield__select" id="t_card_assignee" name="tcard_assignee[user_id]">
              <option value=""></option>
              <% community_users.each do | cu | %>
                <option value="<%= cu.user.id %>" <% if cu.user.id == task.user.try(:id) %>selected<% end%>><%= cu.user.nickname %></option>
              <% end %>
            </select>
            <%= f.label :assignee, class: "mdl-selectfield__label" %>
          </div>
          <div class="mdl-dialog__actions">
            <button class="mdl-button mdl-js-button mdl-button--colored mdl-js-ripple-effect"><%= t('actions.update') %></button>
          </div>
        <% end %>
      <% end %>
    </main>
  </div>
 </div>

app/views/t_cards/_modal_edit.js.erb
$(function () {
  $('#modal-button-edit-task').html('<%= j(render(:partial => 't_cards/modal_edit.html', :locals => { task: @task, community_users: @community_users, chaindata: chaindata })) %>');
  componentHandler.upgradeAllRegistered();
  var picker = new Pikaday({
    field: document.getElementById('datepicker'),
    format: 'D/M/YYYY',
    toString(date, format) {
      const day = date.getDate();
      const month = date.getMonth() + 1;
      const year = date.getFullYear();
      return `<%= t('t_card.edit.deadline.format') %>`;
    },
    onSelect: function(date) {
      $('input[name="t_card[deadline]"]').parent().addClass("is-dirty");
    }
  });
  MicroModal.show('modal-button-edit-task');
});

app/views/t_cards/_t_card.html.erb
  <td class="t-card-status">
      <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect mdl-data-table__select" for="row[<%= t_card.id %>]">
        <%= check_box_tag '', '', t_card.status.closed?, { 'data-id' => t_card.id, 'data-url' => url, :onclick=>
          "$.post($(this).data('url')+ '/tasks/' + $(this).data('id') + '/toggle/', function(data) {
            #{callback}(data);
            if (data && data.message) {
              showSnackbarMessage(data.message);
            }
          });",
          id: "row[#{t_card.id}]", class: "mdl-checkbox__input"} %>
      </label>
  </td>
  <td class="mdl-data-table__cell--non-numeric edit_task_modal_event t-card-title"><%= t_card.title %></td>
  <% if visible_assignee.to_s == "true"  %>
    <td class="assignee-image edit_task_modal_event t-card-assignee">
      <% if t_card.tcard_assignee.nil? %>
        &nbsp;
      <% else %>
        <div class="mdl-tooltip" for="nickname-<%= t_card.id %>"><%= t_card.tcard_assignee.try(:user).try(:nickname) %></div>
        <%= image_tag(avatar_url(t_card.tcard_assignee.user), class: "mdl-chip__contact", id: "nickname-#{t_card.id}", alt: t_card.tcard_assignee.user.nickname) %>
      <% end %>
    </td>
  <% end %>
  <td class="mdl-data-table__cell--non-numeric edit_task_modal_event t-card-deadline" style="white-space: nowrap;"><%= l(t_card.deadline, format: :default) if t_card.deadline %></td>

app/views/t_cards/_t_card.js.erb
$(function () {
  $("#t_card-tr-<%= t_card.id %>").html('<%= j(render(:partial => 't_cards/t_card.html', :locals => {t_card: t_card, visible_assignee: chaindata[:visible_assignee], url: chaindata[:url], callback: chaindata[:callback]})) %>');
  componentHandler.upgradeAllRegistered();
  tableTrTdClickableAjax("t_cards-table-data", "t_card-tr-<%= t_card.id %>", "edit_task_modal_event");
  MicroModal.close('modal-button-edit-task');

  <% if notice %>
    showSnackbarMessage("<%= notice %>");
  <% end %>

  var data = {
    title: "<%= title %>",
    labels: <%= labels %>,
    data: <%= data %>
  };
  <%= chaindata[:callback] %>(data);
});

app/views/t_cards/_t_card_table.html.erb
<div id="t_cards-table">
  <table class="mdl-data-table mdl-shadow--2dp kpter-table" id="t_cards-table-data" data-visible_assignee="<%= visible_assignee %>" data-url="<%= url %>" data-callback="<%= callback %>">
    <thead>
      <tr>
        <th class="mdl-data-table__cell--non-numeric kpter-table-header-title" colspan="2"><%= t('t_card.title', default: 'Tasks') %></th>
        <th colspan="<% if visible_assignee %>2<% else %>1<% end %>">
          <%= link_to t('t_card.status.open', default: 'open'), { action: "refresh_tasks", method: :get, status: TCard.status.open, remote: true }, { id: "open-btn", class: "mdl-color-text--primary kpter-task-open-closed"} %>
          <%= link_to t('t_card.status.close', default: 'close'), { action: "refresh_tasks", method: :get, status: TCard.status.closed, remote: true }, { id: "close-btn", class: "kpter-task-open-closed" } %>
        </th>
      </tr>
      <tr>
        <th class="mdl-data-table__cell--non-numeric"><%= t('t_card.list.done', default: 'Done') %></th>
        <th class="mdl-data-table__cell--non-numeric"><%= t('t_card.list.task', default: 'Task') %></th>
        <% if visible_assignee %>
          <th class="mdl-data-table__cell--non-numeric"><%= t('t_card.list.assignee', default: 'Assignee') %></th>
        <% end %>
        <th class="mdl-data-table__cell--non-numeric"><%= t('t_card.list.deadline', default: 'Deadline') %></th>
      </tr>
    </thead>
    <tbody>
      <% t_cards.each.with_index(1) do |t_card, index| %>
        <tr id="t_card-tr-<%= t_card.id %>" data-href="<%= edit_t_card_path(t_card) %>" data-method="GET" data-url="<%= url %>">
          <%= render :partial => 't_cards/t_card.html', :locals => {t_card: t_card, visible_assignee: visible_assignee, url: url, callback: callback}%>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td class="mdl-data-table__cell--non-numeric" colspan="<% if visible_assignee %>4<% else %>3<% end %>">
          <div class="mdl-paging">
            <%= page_entries_info @t_cards %>
            <%= paginate @t_cards, remote: true, params: {:action => 'refresh_tasks'}%>
          </div>
        </td>
      </tr>
    </tfoot>
  </table>
</div>