config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    post "users/upload", to: "users/registrations#upload", as: "upload_registration"
    post "users/disconnect" => 'users/registrations#disconnect', as: "disconnect_provider"
  end

  get 'welcome/index'
  root 'welcome#index'

  get 'index' => 'welcome#index'
  get 'sp' => 'sp#index'
  get 'confirm' => 'confirm#show'
  get 'mypage' => 'mypages#show'
  get 'terms' => 'terms#show'
  get 'privacy' => 'privacy#show'

  resources :communities, :only => [:new, :create, :show, :edit, :update, :destroy] do
    resources :boards, :only => [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :t_cards, :only => [:edit, :update]

  post 'communities/:id/tasks/:t_card_id/toggle' => 'communities#toggle'
  get 'communities/:id/refresh_tasks' => 'communities#refresh_tasks'
  get 'communities/:id/invitable_users' => 'communities#invitable_users'
  post 'communities/:id/invite' => 'communities#invite'
  post 'communities/:id/accept' => 'communities#accept'
  post 'communities/:id/decline' => 'communities#decline'
  post 'communities/:id/leave' => 'communities#leave'
  post 'communities/:id/remove' => 'communities#remove'
  get 'communities/:id/members' => 'communities#members'
  
  post 'mypage/tasks/:id/toggle' => 'mypages#toggle'
  get 'mypage/refresh_tasks' => 'mypages#refresh_tasks'

  mount ActionCable.server => '/cable'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  class Forbidden < ActionController::ActionControllerError; end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale, :set_mailer_host
  before_action :store_location, :configure_permitted_parameters, if: :devise_controller?
  after_action :store_location

  rescue_from Forbidden, with: :render_403

  def store_location
    # store last url - this is needed for post-login redirect to whatever the user last visited.
    return unless request.get?
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        request.path != root_path &&
        !request.xhr?) # don't store ajax calls
      session[:previous_url] = request.fullpath
    end
  end

  def after_sign_in_path_for(resource)
    session[:next] || mypage_path
  end

  def side_column
    if user_signed_in?
      @communities = User.find_communities_with_user_id(current_user.id)
    end
  end

  # Override
  # See. https://github.com/plataformatec/devise/blob/3722aa62961720eafa5bb5ee6c99b76c26b6be3e/lib/devise/controllers/helpers.rb#L219-L230
  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  # See. https://railsguides.jp/i18n.html
  def set_locale
    I18n.locale = extract_locale_from_subdomain || I18n.default_locale
  end


  # リクエストのサブドメインからロケールを取り出す (https://en.kpter.net:3000のような形式)
  # この動作をローカルPCで行なうためには
  #   127.0.0.1 en.localhost:3000
  # /etc/hostsファイルに上のように記述する必要がある
  def extract_locale_from_subdomain
    parsed_locale = request.subdomains.first
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

  # 本番環境だけ変更
  def default_url_options
    Rails.env.production? ? { protocol: :https }.merge(super) : super
  end
  
  protected
    def configure_permitted_parameters
      # see. https://github.com/plataformatec/devise#strong-parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
    end

  private
    def render_403
      render file: Rails.root.join('public/403.html'), status: :forbidden, layout: false, content_type: 'text/html'
    end
    # リクエストを受けたサーバーのドメインとポートをメールで参照するURLにする
    def set_mailer_host
      ActionMailer::Base.default_url_options[:host] = request.host_with_port
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # avatar image url
  def avatar_url(user)
    if user
      if user.avatar.attached?
        # url = "#{asset_path(user.avatar)}?#{user.lock_version}"
        url = url_for(user.avatar)
      else
        url = asset_path("noimages/profile.png")
      end
    end
  end

  def t_cards_count(community)
    t_card_count = 0
    community.boards.each do |board|
      board.t_cards.each do |t_catd|
        t_card_count += 1 if t_catd.status.open?
      end
    end
    return t_card_count unless t_card_count == 0
  end
end

app/views/application/_google_tag_manager_in_body.html.erb
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P68WJT"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

app/views/application/_google_tag_manager_in_head.html.erb
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-P68WJT');</script>

app/views/application/_header.html.erb
<header class="mdl-layout__header kpter-header">
  <div class="mdl-layout__header-row kpter-menu">
    <% if user_signed_in? %>
      <%= link_to "KPTER", mypage_path, class: "mdl-layout-title kpter-logo-header mdl-color-text--primary" %>
    <% else %>
      <%= link_to "KPTER", root_path, class: "mdl-layout-title kpter-logo-header mdl-color-text--primary" %>
    <% end %>
    <div class="mdl-layout-spacer"></div>
    <% if user_signed_in? %>
      <button class="mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="hdrbtn">
        <i class="material-icons">more_vert</i>
      </button>
      <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right" for="hdrbtn">
        <li class="mdl-menu__item">
          <%= link_to t('registrations.settings.title', default: "Settings"), edit_user_registration_path, class: "kpter-menu-link" %>
        </li>
        <li class="mdl-menu__item">
          <%= link_to t('sessions.sign_out', :default => "Sign out"), destroy_user_session_path, class: "kpter-menu-link" %>
        </li>
      </ul>
    <% else %>
      <nav class="mdl-navigation">
        <%= link_to t('.sign_in', :default => "Sign in"), new_user_session_path, class: "mdl-button mdl-button--primary mdl-js-button mdl-js-ripple-effect" %>
        <%= link_to t('.sign_up', :default => "Sign up"), new_user_registration_path, class: "mdl-button mdl-button--primary mdl-js-button mdl-js-ripple-effect" %>
      </nav>
    <% end %>
  </div>
</header>

app/views/application/_side_column.html.erb
<div class="kpter-drawer mdl-layout__drawer">
  <% if user_signed_in? %>
    <%= link_to "KPTER", mypage_path, class: "mdl-layout-title kpter-logo mdl-color-text--primary" %>
  <% else %>
    <%= link_to "KPTER", root_path, class: "mdl-layout-title kpter-logo mdl-color-text--primary" %>
  <% end %>
  <nav class="mdl-navigation">
    <%= link_to mypage_path, class: "mdl-navigation__link" do %>
      <span class="<% if request.path_info == mypage_path %>mdl-color-text--primary-dark<% end %>"><%= t('mypage.title') %></span>
    <% end %>
    <div class="kpter-drawer-separator"></div>
    <div class="kpter-nav-action">
      <a href class="dialog-button-new-community" onclick="visibleForm('community-form-container', 'create-community-name'); return false;">
        <i class="material-icons md-18">add</i><span><%= t('mypage.add_community') %></span>
      </a>
    </div>
    <div class="kpter-nav-action kpter-nav-form-content" id="community-form-container" style="display:none;">
      <%= form_for communities_path, url: { controller: "/communities", action: "create" } do |f| %>
        <input type="text" name="name" class="kpter-nav-form-input" id="create-community-name" maxlength="32" required="required" >
        <div class="kpter-nav-form-action">
          <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent kpter-nav-form-button mdl-js-ripple-effect">
            <%= t('actions.add', default: 'Add') %>
          </button>
          <button class="mdl-button mdl-js-button kpter-nav-form-button kpter-close-button-text-color mdl-js-ripple-effect" onclick="hiddenForm('community-form-container', 'create-community-name');return false;">
            <%= t('actions.cancel', default: 'Cancel') %>
          </button>
        </div>
      <% end %>
    </div>
    <% communities.each do |cu| %>
      <%= link_to community_path(cu.community), class: "mdl-navigation__link" do %>
        <span class="kpter-drawer-community-name <% if cu.status.inviting? %>kpter-drawer-inviting-text<% end %> <% if current_community == cu.community %>mdl-color-text--primary-dark js-current-community-name<% end %>"><%= cu.community.name %></span>
        <% if cu.status.inviting? %>
          <span class="kpter-drawer-circle"></span>
        <% else %>
          <span class="kpter-drawer-task-count"><%= t_cards_count(cu.community) %></span>
        <% end %>
      <% end %>
    <% end %>
  </nav>
</div>

app/views/application/_tasks.html.erb
<div id="t_cards-table">
  <table class="mdl-data-table mdl-shadow--2dp kpter-table">
    <thead>
      <tr>
        <th class="mdl-data-table__cell--non-numeric kpter-table-header-title" colspan="2">Tasks</th>
        <th colspan="<% if visible_assignee %>2<% else %>1<% end %>">
          <%= link_to "open", { action: "refresh_tasks", method: :get, status: TCard.status.open, remote: true }, { id: "open-btn", class: "mdl-color-text--primary kpter-task-open-closed"} %>
          <%= link_to "close", { action: "refresh_tasks", method: :get, status: TCard.status.closed, remote: true }, { id: "close-btn", class: "kpter-task-open-closed" } %>
        </th>
      </tr>
      <tr>
        <th class="mdl-data-table__cell--non-numeric">Done</th>
        <th class="mdl-data-table__cell--non-numeric">Task</th>
        <% if visible_assignee %>
          <th class="mdl-data-table__cell--non-numeric">Assignee</th>
        <% end %>
        <th class="mdl-data-table__cell--non-numeric">Deadline</th>
      </tr>
    </thead>
    <tbody>
      <% t_cards.each.with_index(1) do |t_card, index| %>
        <tr>
           <td>
              <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect mdl-data-table__select" for="row[<%= index %>]">
                <%= check_box_tag '', '', t_card.status.closed?, { 'data-id' => t_card.id, 'data-url' => url, :onclick=>
                  "$.post($(this).data('url')+ '/tasks/' + $(this).data('id') + '/toggle/', function(data) {
                    #{callback}(data);
                  });",
                  id: "row[#{index}]", class: "mdl-checkbox__input"} %>
              </label>
          </td>
          <td class="mdl-data-table__cell--non-numeric"><%= t_card.title %></td>
          <% if visible_assignee %>
            <% if t_card.tcard_assignee.nil? %>
              <td class="mdl-data-table__cell--non-numeric">&nbsp;</td>
            <% else %>
              <td class="assignee-image">
                <div class="mdl-tooltip" for="<%= t_card.id %>"><%= t_card.tcard_assignee.user.nickname %></div>
                <%= image_tag(avatar_url(t_card.tcard_assignee.user), class: "mdl-chip__contact", id: t_card.id, alt: t_card.tcard_assignee.user.nickname) %>
              </td>
            <% end %>
          <% end %>
          <td class="mdl-data-table__cell--non-numeric" style="white-space: nowrap;"><%= t_card.deadline %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td class="mdl-data-table__cell--non-numeric" colspan="<% if visible_assignee %>4<% else %>3<% end %>">
          <div class="mdl-paging">
            <%= page_entries_info @t_cards %>
            <%= paginate @t_cards, remote: true, params: {:action => 'refresh_tasks'}%>
          </div>
        </td>
      </tr>
    </tfoot>
  </table>
</div>