config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    post "users/upload", to: "users/registrations#upload", as: "upload_registration"
    post "users/disconnect" => 'users/registrations#disconnect', as: "disconnect_provider"
  end

  get 'welcome/index'
  root 'welcome#index'

  get 'index' => 'welcome#index'
  get 'sp' => 'sp#index'
  get 'confirm' => 'confirm#show'
  get 'mypage' => 'mypages#show'
  get 'terms' => 'terms#show'
  get 'privacy' => 'privacy#show'

  resources :communities, :only => [:new, :create, :show, :edit, :update, :destroy] do
    resources :boards, :only => [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :t_cards, :only => [:edit, :update]

  post 'communities/:id/tasks/:t_card_id/toggle' => 'communities#toggle'
  get 'communities/:id/refresh_tasks' => 'communities#refresh_tasks'
  get 'communities/:id/invitable_users' => 'communities#invitable_users'
  post 'communities/:id/invite' => 'communities#invite'
  post 'communities/:id/accept' => 'communities#accept'
  post 'communities/:id/decline' => 'communities#decline'
  post 'communities/:id/leave' => 'communities#leave'
  post 'communities/:id/remove' => 'communities#remove'
  get 'communities/:id/members' => 'communities#members'
  
  post 'mypage/tasks/:id/toggle' => 'mypages#toggle'
  get 'mypage/refresh_tasks' => 'mypages#refresh_tasks'

  mount ActionCable.server => '/cable'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :community_users
  has_many :boards
  validates_length_of :name, in: 1..32

  def find_boards
    Community
    .includes(:boards)
    .joins(:boards)
    .where(id: self.id)
    .map{ |community| community.boards }.flatten
    .sort_by!{ |v| v[:id] }.reverse    # 作成された順(IDの降順)
  end

  def top_of_assignees
    Community
    .includes([:boards => [:t_cards => [:tcard_assignee => :user]]])
    .references(:tcard_assignee => :user)
    .where('communities.id = ? and t_cards.status = ? and users.nickname is not null', self.id, TCard.status.open)
    .group('users.id, users.nickname')
    .order('count_tcard_assignees_id desc, users.id asc')
    .count('tcard_assignees.id')
  end

  def find_tcards(status=TCard.status.open)
    Community
    .includes([:boards => [:t_cards => [:tcard_assignee => :user]]])
    .references(:tcard_assignee => :user)
    .where('communities.id = ? and t_cards.status = ?', self.id, status)
    .map{ |community| community.boards.map{ |board| board.t_cards }}.flatten
    .sort_by!{ |v| [v[:deadline].nil? ? Date.new(9999, 12, 31) : v[:deadline], v[:id]]}  # 期限日の近い順 (同じ期限日内ではIDの昇順。未設定の場合(nil)は常に最後尾)
  end

  def find_users
    Community
    .joins(:community_users => :user)
    .includes(:community_users => :user)
    .where(id: self.id)
    .map{ |community| community.community_users}.flatten
    .sort_by!{ |v| [v[:status].reverse, v[:updated_at]] }    # 参加した順(IDの昇順)
  end

  def find_joining_users
    Community
    .joins(:community_users => :user)
    .includes(:community_users => :user)
    .where('communities.id = ? and community_users.status = ?', self.id, CommunityUser.status.joining)
    .map{ |community| community.community_users}.flatten
    .sort_by!{ |v| [v[:status].reverse, v[:updated_at]] }    # 参加した順(IDの昇順)
  end

  def rest_in_place
    ActiveRecord::Base.transaction do
      tcard_assignees = Community
        .includes([:boards => [:t_cards => :tcard_assignee]])
        .references([:boards => [:t_cards => :tcard_assignee]])
        .where(id: self.id, boards: { community_id: self.id })
        .map{ |community| community.boards.map{ |board| board.t_cards.map{ |t_card| t_card.tcard_assignee }}}.flatten
      TcardAssignee.delete(tcard_assignees)

      t_cards = Community
        .includes([:boards => :t_cards])
        .references([:boards => :t_cards])
        .where(id: self.id, boards: { community_id: self.id })
        .map{ |community| community.boards.map{ |board| board.t_cards }}.flatten
      TCard.delete(t_cards)

      kp_cards = Community
        .includes([:boards => :kp_cards])
        .references([:boards => :kp_cards])
        .where(id: self.id, boards: { community_id: self.id })
        .map{ |community| community.boards.map{ |board| board.kp_cards }}.flatten
      KpCard.delete(kp_cards)

      memos = Community
        .includes([:boards => :memos])
        .references([:boards => :memos])
        .where(id: self.id, boards: { community_id: self.id })
        .map{ |community| community.boards.map{ |board| board.memos }}.flatten
      Memo.delete(memos)

      boards = Community
        .includes(:boards)
        .references(:boards)
        .where(id: self.id, boards: { community_id: self.id })
        .map{ |community| community.boards }.flatten
      Board.delete(boards)

      community_users = Community
        .includes(:community_users)
        .references(:community_users)
        .where(id: self.id)
        .map{ |community| community.community_users }.flatten
      CommunityUser.delete(community_users)

      self.delete
    end
  end

  # {
  # :top_of_assignees=>
  #   [{:name=>"nickname-1", :count=>5},
  #    {:name=>"nickname-2", :count=>4},
  #    {:name=>"nickname-3", :count=>4},
  #    {:name=>"nickname-4", :count=>4},
  #    {:name=>"nickname-5", :count=>4},
  #    {:name=>"others", :count=>22}]
  # }
  def find_top_of_assignees
    top5 = Community.find(self.id).top_of_assignees.first(5)
    others = Community.find(self.id).top_of_assignees.to_a.from(5)
    top_of_assignees = Array.new
    top5.each { |i, j|
      data = { name: i, count: j }
      top_of_assignees.push(data)
    }

    if others.length > 0
      data = { name: t('community.well_balanced.label.others'), count: others.map{ |a| a[1] }.sum }
      top_of_assignees.push(data)
    end

    Hash["top_of_assignees": top_of_assignees]
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_user!, :exists_community?, :allowed_to_display?, :side_column, only: [:show]
  before_action :belongs_to?, except: [:show, :decline, :accept, :create]

  def create
    @community = Community.new(name: params[:name])
    respond_to do |format|
      ActiveRecord::Base.transaction do
        if @community.save
          @community_user = CommunityUser.new(
            user_id: current_user.id,
            community_id: @community.id,
            status: CommunityUser.status.joining
            )
          if @community_user.save
            format.html { redirect_to @community, notice: t('community.created') }
            format.json { render :show, status: :created, location: @community }
          else
            format.html { render :show }
          end
        else
          @error_message = @community.errors.full_messages.first
          format.html { redirect_to :back, alert: @error_message }
        end
      end
    end
  end

  def show
    @community = Community.find(params[:id])
    all_boards = @community.find_boards
    @boards = Kaminari.paginate_array(all_boards).page(params[:page]).per(5)
    all_tcards = @community.find_tcards
    @t_cards = Kaminari.paginate_array(all_tcards).page(params[:page]).per(5)
    @top_of_assignees = @community.find_top_of_assignees
    @invitable_users = User.find_invitable_users(@community)
  end

  def toggle
    updated_tcard = TCard.update_status(params[:t_card_id])

    community = Community.find_by(id: params[:id])
    top_of_assignees = community.find_top_of_assignees
    labels = top_of_assignees[:top_of_assignees].map{|ta| ta[:name]}
    data = top_of_assignees[:top_of_assignees].map{|ta| ta[:count]}

    message = updated_tcard.status.open? ? t('t_card.toggle.open') : t('t_card.toggle.close')

    respond_to do |format|
      format.json { render json: {title: t('community.well_balanced.title'), labels: labels, data: data, message: message}}
    end
  end

  def refresh_tasks
    status = params[:status]
    status ||= TCard.status.open
    @community = Community.find(params[:id])
    all_tcards = @community.find_tcards(status)
    @t_cards = Kaminari.paginate_array(all_tcards).page(params[:page]).per(5)
    @status = status
  end

  def update
    @community = Community.find(params[:id])
    respond_to do |format|
      if @community.update_attributes(name: params[:community][:name])
        @community = Community.find(params[:id])
        message = t('community.update.success')
        format.js { flash.now[:notice] = message }
        format.html { redirect_to @community, notice: message }
        format.json { head :no_content } # 204 No Content
      else
        format.js
        format.json { render json: {message: community.errors.full_messages.first}, status: :unprocessable_entity }
      end
    end
  end

  def invitable_users
    @community = Community.find(params[:id])
    invitable_users = User.find_invitable_users(@community, params[:q])
    respond_to do |format|
      format.js
      format.json { render json: invitable_users.as_json(only: ['id', 'nickname']) }  # セキュリティ的に必要最小限をレスポンスする
    end
  end

  def members
    @members = Community.find(params[:id]).find_users
  end

  def invite
    if params[:id].nil?
      # フロントJSで未選択の場合はボタンdisableにするが、それでもユーザー未指定でリクエストされた場合は、画面をリフレッシュする(chatwork理論)
      flash[:notice] = t('community.invitation.failure')
      redirect_to :action => :show and return
    end

    users = User.where(id: params[:user][:ids])
    community = Community.find(params[:id])
    users.each{ |user|
      unless user.joining?(community)
        user.invited(community)
      end
    }

    respond_to do |format|
      message = t('community.invitation.success', users: users.map(&:nickname).join(', '))
      format.js { flash.now[:notice] = message }
      format.html { redirect_to community, notice: message }
    end

  end

  def accept
    community = Community.find(params[:id])
    current_user.join_in(community)
    flash[:notice] = t('community.invitation.accept')
    redirect_to :action => :show
  end

  def decline
    community = Community.find(params[:id])
    current_user.decline(community)
    flash[:notice] = t('community.invitation.decline')
    redirect_to :controller => :mypages, :action => :show
  end

  def leave
    community = Community.find(params[:id])
    current_user.leave(community)
    flash[:notice] = t('community.leave.success')
    redirect_to :controller => :mypages, :action => :show
  end

  def remove
    community = Community.find(params[:id])
    user = User.find(params[:user_id])
    user.leave(community)

    respond_to do |format|
      message = t('community.remove', nickname: user.nickname)
      format.js { flash.now[:notice] = message }
      format.html { redirect_to community, notice: message }
    end
  end

  def destroy
    community = Community.find(params[:id])
    community.rest_in_place
    flash[:notice] = t('community.destroyed')
    redirect_to :controller => :mypages, :action => :show
  end

  def edit_task
    @task = TCard.find(params[:id]);
  end

  private
    def exists_community?
      # if community does not exists, raise RecordNotFound error
      Community.find(params[:id])
    end

    def allowed_to_display?
      community = Community.find(params[:id])
      unless current_user.allowed_to_display?(community)
        raise Forbidden
      end
    end

    def belongs_to?
      community = Community.find(params[:id])
      unless current_user.joining?(community)
        raise Forbidden
      end
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_boards.html.erb
<% boards.each do |board| %>
  <tr data-href="<%= url_for([community, board]) %>">
     <td class="mdl-data-table__cell--non-numeric">
       <%= board.name %>
    </td>
    <td class="kpter-mute-text">
      <%= board.created_at.to_s(:distance) %>
    </td>
  </tr>
<% end %>

app/views/communities/_delete.html.erb
<div class="mdl-dialog__content kpter-dialog-content2">
  <button class="mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect close">
    <i class="material-icons">close</i>
    <span class="esc">esc</span>
  </button>
  <h4><%= t('community.delete.title', { community_name: current_community.name }) %></h4>
  <%= form_for(current_community, :html => { :method => :delete }) do |f| %>
    <div class="mdl-typography--body-1-color-contrast">
      <%= t('community.delete.body', { community_name: current_community.name }) %>
    </div>
    <ul class="notice">
      <li> <%= t('community.delete.notice1') %></li>
      <li> <%= t('community.delete.notice2') %></li>
      <li> <%= t('community.delete.notice3') %></li>
    </ul>
    <button class="mdl-button mdl-js-button mdl-button--accent float-right mdl-js-ripple-effect"><%= t('community.delete.i_will') %></button>
  <% end %>
</div>

app/views/communities/_edit.html.erb
<div class="mdl-dialog__content kpter-dialog-content2">
  <button class="mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect close">
    <i class="material-icons">close</i>
    <span class="esc">esc</span>
  </button>
  <div class="kpter-form-middle mdl-cell mdl-grid mdl-grid--no-spacing">
    <h4><%= t('community.edit.title') %></h4>
    <%= form_for(current_community, data: { remote: true }) do |f| %>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.text_field :name, class: "mdl-textfield__input", maxlength: 32, required: true %>
        <%= f.label :name, class: "mdl-textfield__label" %>
      </div>
      <button class="mdl-button mdl-js-button mdl-button--colored float-right mdl-js-ripple-effect"><%= t('actions.update') %></button>
    <% end %>
  </div>
</div>

app/views/communities/_invitable_users.html.erb
<div class="mdl-dialog__content kpter-dialog-content">
  <button class="mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect close">
    <i class="material-icons">close</i>
    <span class="esc">esc</span>
  </button>
  <div class="kpter-invitable-content">
    <h4><%= t('community.invitable_users.title', {community_name: community.name}) %></h4>
    <%= form_for community, :url => {:action => 'invite'}, :method => :post, remote: true do |f| %>
      <div class="kpter-invitable-select">
        <%= select_tag 'user[ids]', "", class: "select2-user-multiple", multiple: true %>
        <%= submit_tag t('community.invitable_users.actions.invite'), class: "mdl-button mdl-js-button mdl-button--colored mdl-button--raised kpter-invite-button mdl-js-ripple-effect", disabled: true %>
      </div>
      <script>
        settingDialog("dialog-button-invitable-users", "invitable-users-dialog");
      </script>
    <% end %>
  </div>
</div>

app/views/communities/_inviting.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--6-col">
    <div class="kpter-contents">
      <div class="kpter-sub-heading">
        <div class="kpter-sub-title">
          <div class="mdl-typography--body-2-color-contrast"><%= @community.name %></div>
        </div>
        <div class=“clarifix”></div>
      </div>
      <div class="kpter-sub-contents">
        <div class="mdl-typography--body-1-color-contrast">
          You received an invitation to join a community.<br>
          Do you accept or decline?
        </div>
      </div>
      <div class="kpter-chip-action-container">
        <div class="kpter-chip-actions">
          <div class="kpter-chip-action">
            <%= form_for @community, :url => {:action => 'decline'}, :method => :post do |f| %>
              <%= button_tag "Decline", class: "mdl-chip mdl-color--primary mdl-color-text--primary-contrast kpter-chip-action-m" do %>
                <span class="mdl-chip__text">Decline</span>
              <% end %>
            <% end %>
          </div>
          <div class="kpter-chip-action">
            <%= form_for @community, :url => {:action => 'accept'}, :method => :post do |f| %>
              <%= button_tag "Decline", class: "mdl-chip mdl-color--cyan-300 mdl-color-text--primary-contrast kpter-chip-action-m" do %>
                <span class="mdl-chip__text">Accept</span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/communities/_joining.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--8-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
    <div class="kpter-sub-heading">
      <div class="kpter-sub-title">
        <div class="mdl-typography--body-2-color-contrast js-current-community-name"><%= @community.name %></div>
      </div>
      <div class="kpter-settings">
        <%= link_to community_path + '/members', {:remote => true, class: "mdl-button mdl-js-button mdl-button--icon"} do %>
          <i class="material-icons md-18">person</i>
        <% end %>
        <button id="settings" class="mdl-button mdl-js-button mdl-button--icon">
          <i class="material-icons md-18">settings</i>
        </button>
        <ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect kpter-menu" for="settings">
          <li class="mdl-menu__item">
            <%= link_to community_path + '/invitable_users', {:remote => true, class: "kpter-menu-link dialog-button-invitable-users"} do %><%= t("community.menus.invite") %><% end %>
          </li>
          <li class="mdl-menu__item"><a href="#" class="dialog-button-edit"><%= t("community.menus.edit") %></a></li>
          <li class="mdl-menu__item mdl-menu__item--full-bleed-divider"><a href="#" class="dialog-button-leave"><%= t("community.menus.leave") %></a></li>
          <li class="mdl-menu__item"><a href="#" class="dialog-button-delete"><%= t("community.menus.delete") %></a></li>
        </ul>
      </div>
    </div>
    <%= render :partial => "t_cards/t_card_table", :locals => { t_cards: @t_cards, visible_assignee: true, url: @community.id, status: @status, callback: "chartTopOfAsignee" } %>
  </div>
  <div class="mdl-cell mdl-cell--4-col mdl-cell--hide-tablet mdl-cell--hide-phone">
    <canvas id="topOfAsignee" width="400" height="400"></canvas>
  </div>
</div>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--8-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
      <div id="board-list">
        <table class="mdl-data-table mdl-shadow--2dp kpter-table" id="board-table">
          <thead>
            <tr>
              <th class="mdl-data-table__cell--non-numeric kpter-table-header-title"><%= t('community.board.title') %></th>
              <th>
              <button class="mdl-button mdl-js-button mdl-button--icon dialog-button-new-board mdl-button--fab mdl-button--mini-fab board-add-button">
                <i class="material-icons" id="board-add-button">add</i>
                <div class="mdl-tooltip" data-mdl-for="board-add-button">
                  <%= t('community.board.actions.create') %>
                </div>
              </button>
              </th>
            </tr>
          </thead>
          <tbody>
            <%= render :partial => 'boards', :locals => {boards: @boards, community: @community} %>
          </tbody>
          <% if @boards.empty? %>
            <tfoot>
              <tr>
                <td class="mdl-data-table__cell--non-numeric" colspan="2">
                  <div class="mdl-paging">
                    No boards
                  </div>
                </td>
              </tr>
            </tfoot>
          <% end %>
        </table>
      </div>
      <div class="view-more mdl-typography--body-1-color-contrast">
        <%= link_to_next_page(@boards, 'View more', remote: true, id: 'view-more', class: 'mdl-button mdl-js-button mdl-button--raised') %>
      </div>
  </div>
</div>

<!-- invite others -->
<dialog id="invitable-users-dialog" class="mdl-dialog kpter-dialog-full-screen">
  <%= render :partial => 'invitable_users', :locals => {invitable_users: @invitable_users, community: @community} %>
</dialog>

<!-- leave -->
<dialog id="dialog-button-leave" class="mdl-dialog kpter-dialog-full-screen">
  <%= render :partial => 'leave', :locals => {current_community: @community} %>
</dialog>

<!-- delete -->
<dialog id="dialog-button-delete" class="mdl-dialog kpter-dialog-full-screen">
  <%= render :partial => 'delete', :locals => {current_community: @community} %>
</dialog>

<!-- edit -->
<dialog id="dialog-button-edit" class="mdl-dialog kpter-dialog-full-screen">
  <%= render :partial => 'edit', :locals => {current_community: @community} %>
</dialog>

<!-- member list -->
<div class="modal micromodal-slide" id="modal-button-member" aria-hidden="true">
  <%= render :partial => 'members', :locals => {current_community: @community, members: @members} %>
</div>

<!-- task -->
<div class="modal modal__kptercard micromodal-slide" id="modal-button-edit-task" aria-hidden="true">
  <%= render :partial => 't_cards/modal_edit', :locals => {task: @task, community_users: @community_users} %>
</div>

<!-- new board -->
<dialog id="dialog-button-new-board" class="mdl-dialog kpter-dialog-full-screen">
  <%= render :partial => 'new_board', :locals => {current_community: @community}%>
</dialog>

<% content_for :extra_js do %>
  <%= javascript_include_tag 'communities' %>
  <script>
    const title = "<%= t('community.well_balanced.title') %>"
    <% if @top_of_assignees.empty? %>
      var labels = []
      var data = []
    <% else %>
      var labels = [<% @top_of_assignees[:top_of_assignees].each do |v| %>"<%= v[:name] %>",<% end %>]
      var data = [<% @top_of_assignees[:top_of_assignees].each do |v| %>"<%= v[:count] %>",<% end %>]
    <% end %>
    var datas = {
      "title": title,
      "labels": labels,
      "data": data
    }
    chartTopOfAsignee(datas);
  </script>
<% end %>

app/views/communities/_members.html.erb
<div class="modal__overlay" tabindex="-1" data-micromodal-close>
  <div class="modal__container mdl-shadow--2dp" role="dialog" aria-modal="true" aria-labelledby="modal-1-title">
    <header class="modal__header">
      <h2 class="modal__title" id="modal-1-title">
        <%= t("community.members_list.title", default: "members list") %>
      </h2>
      <button class="modal__close" aria-label="Close modal" data-micromodal-close></button>
    </header>
    <main class="modal__content" id="modal-1-content">
      <div class="mdl-list kpter-member-list">
        <% if members.nil? %>
          <%= t("community.members_list.nobody_is_here", default: "Nobody is here") %>
        <% else %>
          <% members.each_with_index do |cu, i| %>
            <div class="mdl-list__item mdl-list__item--two-line">
              <span class="mdl-list__item-primary-content">
                <% if cu.status.joining? %>
                  <%= image_tag(avatar_url(cu.user), :class => "mdl-list__item-avatar", :alt => "#{cu.user.nickname}") %>
                  <span><%= cu.user.nickname %><% if current_user == cu.user %><span class="joining-you">&nbsp;(<%= t("community.members_list.you", default: "you") %>)</span><% end %></span>
                <% else %>
                  <%= image_tag(avatar_url(cu.user), :class => "mdl-list__item-avatar inviting-avatar", :alt => "#{cu.user.nickname}") %>
                  <span class="inviting-text"><%= cu.user.nickname %></span>
                  <span class="mdl-list__item-sub-title">(<%= t("community.members_list.inviting", default: "inviting") %>)</span>
                <% end %>
              </span>
              <% if current_user != cu.user %>
                <button class="mdl-list__item-secondary-action mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="btn-<%= i %>">
                  <i class="material-icons md-18 mute-color">more_horiz</i>
                </button>
                <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right kpter-menu" for="btn-<%= i %>">
                  <li class="mdl-menu__item">
                    <%= link_to t("community.members_list.remove"), community_path + "/remove?user_id=#{cu.user.id}", :method => :post %>
                  </li>
                </ul>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </main>
  </div>
 </div>

app/views/communities/_new_board.html.erb
<div class="mdl-dialog__content kpter-dialog-content2">
  <button class="mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect close">
    <i class="material-icons">close</i>
    <span class="esc">esc</span>
  </button>
  <div class="kpter-form-middle mdl-cell mdl-grid mdl-grid--no-spacing">
    <h4><%= t('community.board.actions.create') %></h4>
    <%= form_for(current_community, url: community_boards_path(current_community), method: :post) do |f| %>
      <%= f.fields_for :boards do |b| %>
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <%= b.text_field :name, class: "mdl-textfield__input", value: "", maxlength: 64, required: true %>
          <label class="mdl-textfield__label" for="community_boards_name"><%= t('activerecord.attributes.board.name') %></label>
        </div>
      <% end %>
      <button class="mdl-button mdl-js-button mdl-button--colored float-right mdl-js-ripple-effect"><%= t('actions.create') %></button>
    <% end %>
  </div>
</div>

app/views/communities/invitable_users.js.erb
$(function () {
  $('#invitable-users-dialog').html('<%= j(render(:partial => 'invitable_users', :locals => { invitable_users: @invitable_users, community: @community})) %>');

  // 招待可能ユーザーの検索
  $('.select2-user-multiple').select2({
    dropdownParent: $('.kpter-invitable-select'),
    placeholder: "<%= t('community.invitable_users.select.placeholder') %>",
    minimumInputLength: 1,
    language: {
        inputTooShort: function(args) {
          // args.maximum is the maximum allowed length
          // args.input is the user-typed text
          return "<%= t('community.invitable_users.select.too_short', {mimimum_input_length: 1}) %>";
        },
        noResults: function() {
          return "<%= t('community.invitable_users.select.not_found') %>";
        },
        searching: function() {
          return "<%= t('community.invitable_users.select.searching') %>";
        }
      },
    ajax: {
      url: "<%= community_path + '/invitable_users' %>",
      dataType: 'json',
      delay: 350,
      processResults: function (data) {
        return { results: $.map(data, function(user) {
            return { id: user.id, text: user.nickname };
          })
        };
      }
    }
  });

  // 招待するユーザーが一人も選択されていない場合は、Inviteボタンを非活性にする
  $('.select2-user-multiple').on("change", function(){
    if($('.select2-container').find('.select2-selection__choice').length == 0) {
      $(".kpter-invite-button").prop("disabled", true);
    } else {
      $(".kpter-invite-button").prop("disabled", false);
    }
  });
});

app/views/communities/joining.js.erb
$("#board-list tbody").append("<%= escape_javascript(render( :partial => 'boards', :locals => {boards: @boards, community: @community})) %>");
$("#view-more").replaceWith("<%= escape_javascript(link_to_next_page @boards, 'View more', :remote => true, :id => :'view-more', class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect') %>");
tableClickable("board-table");

app/views/communities/members.js.erb
$(function () {
  $('#modal-button-member').html('<%= j(render(:partial => 'members', :locals => { current_community: @community, members: @members })) %>');
  // modal settings
  MicroModal.init({
    disableScroll: true
  });
  MicroModal.show('modal-button-member');
  // ...を機能させるため
  componentHandler.upgradeAllRegistered();
});

app/views/communities/refresh_tasks.js.erb
$(function () {
  $('#t_cards-table').html('<%= j(render(:partial => 't_cards/t_card_table', :locals => { t_cards: @t_cards, visible_assignee: true, url: @community.id, status: @status, callback: "chartTopOfAsignee" })) %>');
  <% if @status == TCard.status.open %>
    $("#open-btn").addClass('mdl-color-text--primary');
    $("#close-btn").removeClass('mdl-color-text--primary');
  <% else %>
    $("#open-btn").removeClass('mdl-color-text--primary');
    $("#close-btn").addClass('mdl-color-text--primary');
  <% end %>
  <% # カード編集のモーダルイベントを設定する %>
  tableTdClickableAjax("t_cards-table-data", "edit_task_modal_event");
  <% # see. https://github.com/google/material-design-lite/wiki/How-the-Component-Handler-works %>
  componentHandler.upgradeAllRegistered();
});

app/views/communities/show.html.erb
<% content_for :head_title do %>
  <%=@community.name%>
<% end %>
<% content_for :header_layout_type do %>
  mdl-layout--fixed-drawer
<% end %>

<% if current_user.joining?(@community) %>
  <%= render :partial => 'joining' %>
<% else %>
  <%= render :partial => 'inviting' %>
<% end %>

app/views/communities/show.js.erb
$("#board-list tbody").append("<%= escape_javascript(render( :partial => 'boards', :locals => {boards: @boards, community: @community})) %>");
$("#view-more").replaceWith("<%= escape_javascript(link_to_next_page @boards, 'View more', :remote => true, :id => :'view-more', class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect') %>");
tableClickable("board-table");