config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    post "users/upload", to: "users/registrations#upload", as: "upload_registration"
    post "users/disconnect" => 'users/registrations#disconnect', as: "disconnect_provider"
  end

  get 'welcome/index'
  root 'welcome#index'

  get 'index' => 'welcome#index'
  get 'sp' => 'sp#index'
  get 'confirm' => 'confirm#show'
  get 'mypage' => 'mypages#show'
  get 'terms' => 'terms#show'
  get 'privacy' => 'privacy#show'

  resources :communities, :only => [:new, :create, :show, :edit, :update, :destroy] do
    resources :boards, :only => [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :t_cards, :only => [:edit, :update]

  post 'communities/:id/tasks/:t_card_id/toggle' => 'communities#toggle'
  get 'communities/:id/refresh_tasks' => 'communities#refresh_tasks'
  get 'communities/:id/invitable_users' => 'communities#invitable_users'
  post 'communities/:id/invite' => 'communities#invite'
  post 'communities/:id/accept' => 'communities#accept'
  post 'communities/:id/decline' => 'communities#decline'
  post 'communities/:id/leave' => 'communities#leave'
  post 'communities/:id/remove' => 'communities#remove'
  get 'communities/:id/members' => 'communities#members'
  
  post 'mypage/tasks/:id/toggle' => 'mypages#toggle'
  get 'mypage/refresh_tasks' => 'mypages#refresh_tasks'

  mount ActionCable.server => '/cable'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: "google_tag_manager_in_head" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="content-style-type" content="text/css" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta name="robots" content="noodp" />
    <title><%= yield :head_title %></title>
    <link rel="stylesheet" type='text/css' href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel='stylesheet' type='text/css' href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800">
    <%= stylesheet_link_tag 'mdl/1.3.0/material.kpter-pink.min', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <% # append extra stylesheet tags %>
    <%= yield :extra_stylesheet %>
    <% # dialog-polyfill  %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.9/dialog-polyfill.css" rel="stylesheet" />
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.9/dialog-polyfill.min.js"></script>

    <%= javascript_include_tag 'mdl/1.3.0/material', defer: "defer" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js"></script>
    <%= javascript_include_tag 'application' %>
    <% # select2 requires jquery. So it need to describes after jquery %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" />
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
    <% # pikaday see. https://github.com/dbushell/Pikaday  %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
    <% # micromodal see. https://micromodal.now.sh/%>
    <script defer src="https://unpkg.com/micromodal/dist/micromodal.min.js"></script>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="57x57" href="/images/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/images/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/icons/favicon-16x16.png">
    <link rel="manifest" href="/images/icons/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/images/icons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body>
    <%= render partial: "google_tag_manager_in_body" %>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header <%= yield(:header_layout_type) %>">
      <%= render partial: "header" %>
      <% if user_signed_in? %>
        <%= render partial: "side_column", locals: { communities: @communities, current_community: @community } %>
      <% end %>
      <main class="mdl-layout__content">
        <div class="page-content">
          <%= yield %>
        </div>
      </main>
    </div>
    <%= render partial: "shared/messages" %>
    <% # append extra js tags %>
    <%= yield :extra_js %>
  </body>
</html>

app/views/layouts/board_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: "google_tag_manager_in_head" %>
  <title><%= yield :head_title %></title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= stylesheet_link_tag  'mdl/1.3.0/material.kpter-pink.min', media: 'all' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag  'boards/default', media: 'all' %>
  <%= stylesheet_link_tag  'boards/component', media: 'all' %>
  <%= stylesheet_link_tag  'boards/style', media: 'all' %>
  <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
  <script src="https://unpkg.com/micromodal/dist/micromodal.min.js"></script>
  <%= javascript_tag do %>
    window.kp_cards = <%= raw @board.kp_cards.to_json(include: [:likes, :owner]) %>;
    window.t_cards = <%= raw @board.t_cards.to_json(include: [:likes, :owner, :user]) %>;
    window.memos = <%= raw @board.memos.to_json %>;
    window.current_user = <%= raw current_user.to_json %>;
    window.no_img = "<%= @no_img %>";
  <% end %>
  <%= javascript_include_tag 'cable' %>
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "google_tag_manager_in_body" %>
  <div id="wrapper">
    <%= yield %>
  </div>
  <!-- member list -->
  <div class="modal micromodal-slide" id="modal-button-member" aria-hidden="true">
    <%= render :partial => 'members', :locals => {current_community: @board.community, members: @members}  %> 
  </div>
  <!-- /#wrapper -->
  <%= debug(params) if Rails.env.development? %>
  <%= javascript_include_tag 'cable' %>
  <%= javascript_include_tag 'boards/cards' %>
</body>
</html>

app/views/layouts/email.html.erb
<div style="background-color:#f4f4f4;width:100%;padding:10px 0px 10px 0px;font-family:'Hiragino Kaku Gothic Pro',Meiryo,Osaka,helvetica,arial,clean,sans-serif">
  <div style="margin:0px auto 0px auto;width:600px">
    <div style="text-align:center;padding:10px 0px 14px 0px">
      <img src="<%= url_to_image("app_icon.png", host: "https://kpter.net") %>" alt="KPTER App" style="border-radius: 9px; margin: 0 0 24px 0;">
    </div>
    <div style="text-align:left;background-color:#ffffff;border:#d9d9d9 1px solid;color:#232323;font-size:14px;padding:2% 6% 2% 6%;">
      <%= yield %>
      </p>
        <%= t('devise.mailer.ending_html') %><br>
      </p>
      <p>
        <%= t('devise.mailer.support_html') %>
      </p>
    </div>
    <div style="vertical-align:middle;color:#232323;text-align:center;padding:20px 0px 10px 0px;font-size:12px"></div>
  </div>
</div>

app/views/layouts/sp_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: "google_tag_manager_in_head" %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="KPTでの振り返り、はじめてみませんか？KPTERは、振り返り手法KPTをもちいて、プロジェクトメンバー、友だち、恋人、夫婦などで普段いえないことを共有できるシンプルかつ強力な新しいコミュニケーションツールです。">
    <meta http-equiv="content-language" content="ja" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="content-style-type" content="text/css" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta name="robots" content="noodp" />
    <meta property="og:title" content="KPTER" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="KPTでの振り返り、はじめてみませんか？KPTerは、振り返り手法KPTをもちいて、プロジェクトメンバー、友だち、恋人、夫婦などで普段いえないことを共有できるシンプルかつ強力な新しいコミュニケーションツールです。" />
    <meta property="og:url" content="https://kpter.net/" />
    <meta property="og:image" content="https://kpter.net/images/og.png"/>
    <meta property="og:site_name" content="KPTER" />
    <title>KPTER</title>
    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag 'sp/bootstrap/css/bootstrap.min', media: 'all' %>
    <!-- Custom Fonts -->
    <%= stylesheet_link_tag 'sp/font-awesome/css/font-awesome.min', media: 'all' %>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <!-- Plugin CSS -->
    <%= stylesheet_link_tag  'sp/magnific-popup/magnific-popup', media: 'all' %>
    <!-- Theme CSS -->
    <%= stylesheet_link_tag 'sp/style', media: 'all' %>
    <%= stylesheet_link_tag 'sp/creative', media: 'all' %>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="57x57" href="/images/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/images/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/icons/favicon-16x16.png">
    <link rel="manifest" href="/images/icons/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/images/icons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body id="page-top">
    <%= render partial: "google_tag_manager_in_body" %>
    <%= render :partial => "header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/welcome_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: "google_tag_manager_in_head" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="content-style-type" content="text/css" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta name="robots" content="noodp" />
    <title><%= yield :head_title %></title>
    <meta name="description" content="<%= yield :meta_description %>" />
    <%= stylesheet_link_tag 'theDocs/1.4.0/theDocs.all', media: 'all' %>
    <%= stylesheet_link_tag 'welcome/welcome', media: 'all' %>
    <%= stylesheet_link_tag 'style', media: 'all' %>
    <% # append extra stylesheet tags %>
    <%= yield :extra_stylesheet %>
    <link href='https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,800%7COpen+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800%7CMontserrat:400,700' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="57x57" href="/images/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/images/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/icons/favicon-16x16.png">
    <link rel="manifest" href="/images/icons/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/images/icons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body>
    <%= render partial: "google_tag_manager_in_body" %>
    <header class="site-header sticky navbar-transparent navbar-sm">
      <nav class="navbar navbar-default navbar-light">
        <div class="container">
          <div class="navbar-header" style="float: left;">
            <%= link_to 'KPTER', root_path, class: "kpter-logo" %>
          </div>
          <div id="navbar" class="navbar-collapse" aria-expanded="true" role="banner">
            <ul class="nav navbar-nav navbar-right" style="float: right !important;">
              <li style="float: left;"><%= link_to t('.sign_in', :default => "Sign in"), new_user_session_path %></li>
              <li class="hero" style="float: left;"><%= link_to t('.sign_up', :default => "Sign up"), new_user_registration_path %></li>
            </ul>
          </div>
        </div>
      </nav>
      <%= yield :header %>
    </header>
    <aside class="col-md-3 sidebar">
      <ul class="sidenav">
        <li class="section">
          <ul>
            <li class="item"><%= link_to t('.sign_in', :default => "Sign in"), new_user_session_path %></li>
            <li class="item"><%= link_to t('.sign_up', :default => "Sign up"), new_user_registration_path %></li>
          </ul>
        </li>
      </ul>
    </aside>
    <main>
      <%= yield %>
    </main>
    <footer class="site-footer">
      <div class="container">
        <a id="scroll-up" href="#"><i class="fa fa-angle-up"></i></a>
        <div class="row">
          <div class="col-md-6 col-sm-6">
            <p>&copy; <%= Time.now.year %> KPTER</p>
          </div>
          <div class="col-md-6 col-sm-6">
            <ul class="footer-menu">
              <li><%= link_to t('terms.label', default: "Terms"), terms_path %></li>
              <li><%= link_to t('privacy_policy.label', default: "Privacy Policy"), privacy_path %></li>
              <li><%= link_to t('contact.label', default: "Contact"), "https://form.run/@kpter-contact" %></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <%= javascript_include_tag 'jquery' %>
    <%= javascript_include_tag 'theDocs/1.4.0/theDocs.all' %>
    <% # append extra js tags %>
    <%= yield :extra_js %>
  </body>
</html>